FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /backend

COPY . .

RUN dotnet publish -c Release -o ./publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /backend/publish .
ENTRYPOINT ["dotnet", "TaskBoard.PL.dll"]